#!/usr/bin/env bash
# Vimigo - connect your WhatsApp.
#
#   curl -fsSL https://raw.githubusercontent.com/tengkusyafiq/vimigo-company-os-setup/main/install-whatsapp-mac.sh | bash
set -eu

# Its own release tag, deliberately not the repository's v1.0 - see the Windows
# one-liner for why. Both must name the same tag.
RELEASE='https://github.com/tengkusyafiq/vimigo-company-os-setup/releases/download/whatsapp-v1.12/vimigo-whatsapp-mac-v1.12.zip'
# The trust anchor. See the Windows one-liner for why the manifest inside the
# zip is not one. Regenerated by publish-release.py from the built asset.
ZIP_SHA256='af7d050b6c090e19ce891c00eec76dfc4bbe494d773b77d38789dffb24a97bef'
ROOT="$HOME/Library/Application Support/Vimigo/whatsapp"

stop_here() {
    printf '\n  \033[31m%s\033[0m\n\n' "$1"
    printf '  Nothing was changed. Tell Vimigo support what this said.\n\n'
    exit 1
}

# For after the doer has been handed control. Deliberately NOT stop_here: by
# then the install root exists, the doer is in it, and the doer may have got
# some way into the real work before it fell over - so "Nothing was changed"
# would be a lie, and the owner would tell support the wrong thing.
gave_up() {
    printf '\n  \033[31m%s\033[0m\n\n' 'Something went wrong setting this up. Please tell Vimigo support.'
    printf '  Tell them what you saw on this screen.\n\n'
    exit 1
}

# ASCII only, on purpose. The main setup draws its banner in box-drawing
# characters, but it controls the terminal encoding before it does; this runs
# through `curl | bash` in whatever window the owner happened to open, and a
# banner that arrives as mojibake is worse than no banner at all. Same three
# lines as the Windows one-liner, character for character.
printf '\n  \033[36m==============================================\033[0m\n'
printf '  \033[36m   V I M I G O   W H A T S A P P   S E T U P\033[0m\n'
printf '  \033[36m==============================================\033[0m\n\n'

# Staged in a temp directory. The install root is not created, and nothing is
# written into it, until there is something verified to put there.
#
# The `|| stop_here` sits on the ASSIGNMENT, not on a line after it. Under
# `set -e` a failing command substitution kills the script where it stands, so
# a guard written as a following line is never reached and its sentence is dead
# code - the owner would get a blank screen and no instruction. Proven:
# `set -eu; WORK="$(false)"; [ -n "$WORK" ] || echo GUARD` exits 1 in silence.
# Being part of a `||` list is also what suspends `set -e` for the assignment.
WORK="$(mktemp -d 2>/dev/null || mktemp -d -t vimigo-wa)" || stop_here 'Could not get started. Please tell Vimigo support.'
[ -n "$WORK" ] && [ -d "$WORK" ] || stop_here 'Could not get started. Please tell Vimigo support.'
trap 'rm -rf "$WORK"' EXIT

printf '  Downloading. This takes a moment.\n'
# -fsL, not -fsSL. -S re-enables exactly the errors -s just turned off, and
# curl's errors are the wrong kind of sentence entirely: "curl: (6) Could not
# resolve host: ..." and "curl: (37) Could not open file /var/folders/...".
# 2>/dev/null on top, because --retry also narrates its own retries.
#
# The timeouts. curl has no transfer timeout of its own, so without these a
# download that stops moving leaves the Mac on "This takes a moment." forever,
# with no error and no way out but closing the window. The event case is not a
# dead connection, it is ~100 laptops pulling 28 MB through one venue hotspot:
#   --connect-timeout 30  a hotspot that has dropped off the network says so in
#                         half a minute rather than in silence.
#   --speed-limit/-time   under 1 KB/s for a full minute is stalled, not slow.
#                         This is the guard that actually fires on a wedged
#                         transfer, and it fires in about a minute.
#   --max-time 1200       the outer ceiling: 28 MB inside 20 minutes is 24 KB/s
#                         sustained. Anything below that was never going to
#                         finish, and 20 minutes is long enough that a badly
#                         contended hotspot is not cut off mid-download.
#   --retry 2             a dropped connection gets two more goes. The owner's
#                         only other move is to run the whole thing again.
curl -fsL --connect-timeout 30 --speed-limit 1024 --speed-time 60 \
     --max-time 1200 --retry 2 --retry-delay 5 \
     -o "$WORK/download.zip" "$RELEASE" 2>/dev/null \
    || stop_here 'Could not download it. Check you are online and try again.'

# Before extracting, not after. The extractor below is silenced either way, but
# a download that failed verification has no business being opened at all - and
# a refusal that names the pin is the honest sentence, not "could not be opened".
ACTUAL="$(shasum -a 256 "$WORK/download.zip" | awk '{print $1}' | tr '[:upper:]' '[:lower:]')"
EXPECTED="$(printf '%s' "$ZIP_SHA256" | tr '[:upper:]' '[:lower:]')"
# Both sides folded, as the Windows one-liner does with ToLowerInvariant. shasum
# emits lowercase, so the only way these can differ in case is publish-release.py
# writing an uppercase pin into the line above - which would then fail EVERY mac
# install while every windows install passed. Not a difference worth discovering
# on the day.
[ "$ACTUAL" = "$EXPECTED" ] || { rm -f "$WORK/download.zip"; stop_here 'That download did not arrive properly. Please try again.'; }

# ditto first, unzip second, both silenced - the same shape as the shipped
# public-install-mac.sh. ditto ships with macOS, understands the archive format
# Apple produces, and keeps the executable bit on what it extracts.
#
# The silencing is the point, not a tidy-up. unzip's -q hides its progress but
# NOT its errors: handed something that is not an archive it prints four lines
# about end-of-central-directory signatures and names the temporary file three
# times. That is the last thing a 60-year-old owner should be reading.
ditto -x -k "$WORK/download.zip" "$WORK/extracted" 2>/dev/null \
    || unzip -oq "$WORK/download.zip" -d "$WORK/extracted" 2>/dev/null \
    || stop_here 'That download could not be opened. Please try again.'

# curl does not set the quarantine flag - browsers and the App Store do - but
# ditto restores whatever the archive itself carries, and macOS cp copies
# extended attributes across with the file. So this covers the one thing that
# leaves this tree: vimigo-whatsapp.sh, copied into the install root below.
#
# It does NOT cover the binaries, and is not meant to. They are never taken
# from here - install_binaries re-extracts them from download.zip into a tree
# of its own - so install_binaries has to clear quarantine on its own tree
# before it copies them into <root>/bin, exactly as the Windows doer calls
# Unblock-File on its extraction temp before copying. That is Task 11's line to
# write; nothing this script can do reaches those files.
xattr -dr com.apple.quarantine "$WORK/extracted" 2>/dev/null || true

[ -f "$WORK/extracted/vimigo-whatsapp.sh" ] || stop_here 'That download did not contain the setup.'

# Only now, and only the doer. install_binaries is the one thing that ever
# writes <root>/bin.
mkdir -p "$ROOT"
cp "$WORK/extracted/vimigo-whatsapp.sh" "$ROOT/vimigo-whatsapp.sh"
chmod +x "$ROOT/vimigo-whatsapp.sh"

# < /dev/tty is load-bearing.
#
# Under `curl … | bash`, stdin is the exhausted pipe, so every prompt reads
# EOF instantly: the "can't scan? use a code" path asks for the phone number,
# read returns empty, to_e164 "" returns "", and the pair-phone POST goes out
# with no number and fails. Both shipped mac one-liners already carry this
# line for the same reason (public-install-mac.sh:103-109).
#
# `[ -r /dev/tty ]` only tests the device node's permission bits, which stay
# readable even with no controlling terminal at all - actually opening it
# then fails with ENXIO, and that raw "No such device or address" reaches the
# owner's screen instead of one plain sentence, before the doer ever runs.
# Attempting the open for real, inside a subshell so a failure cannot leave
# any redirection behind in this shell, is what actually answers "can this be
# read" - proven both ways under a genuinely terminal-less invocation.
# --zip-sha256 is $ACTUAL: the exact 64-character lowercase hex already verified
# above. The doer persists it into installed.json's zip_sha256, and every later
# repair (--fix, --reinstall) reads it back from there - by then there is no
# one-liner in front of the owner to hand it a fresh pin. Leaving it out strands
# every mac repair behind a placeholder that can never validate, which is the
# same Critical the windows one-liner already carries a comment about. Flags, not
# positionals: the doer's other entry points are verbs (--doctor, --fix,
# --reinstall, --reconnect), so a bare path would be one typo away from being
# read as one. See .superpowers/sdd/2026-08-10-whatsapp-one-click/pin-interface.md.
#
# `|| gave_up` on BOTH branches. Without it, `set -e` ends the script the
# instant the doer returns non-zero and the last thing on screen is whatever
# the doer printed on its way down - with no sentence and no instruction. The
# shape that makes this real is a vimigo-whatsapp.sh that got CRLF line endings
# somewhere between the build and the zip: bash 3.2 prints ": command not
# found" once per line and stops, and the owner is left staring at it. Being
# part of a `||` list is also what stops `set -e` from beating the guard to it.
if ( : < /dev/tty ) 2>/dev/null; then
    bash "$ROOT/vimigo-whatsapp.sh" --zip-path "$WORK/download.zip" --zip-sha256 "$ACTUAL" < /dev/tty || gave_up
else
    # No terminal at all. The install still runs; every prompt in the doer
    # fails closed rather than answering itself with an empty string.
    bash "$ROOT/vimigo-whatsapp.sh" --zip-path "$WORK/download.zip" --zip-sha256 "$ACTUAL" || gave_up
fi
